### ISSUE TITLE
Proof-read single-arc propagation page

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#26] opened 2021-11-05 11:46 UTC
Proofread [this](https://tudat-space.readthedocs.io/en/latest/_src_user_guide/running_simulation/single_arc.html) page.

(please check when done)
- [x] @jo11he 
- [x] @FilippoOggionni

**Comment by FilippoOggionni** [comment] 2021-11-05 13:50
I reviewed the page (see [this](https://github.com/tudat-team/tudat-space/commit/db6033f394f60d902e1460e6c975b55c354ddb20) commit on the `single-arc-propagator-review` branch), waiting for @jo11he to provide his modifications on the same branch, then I will open a pull request and link it here, so that @DominicDirkx can merge and close the issue.

**Comment by jo11he** [comment] 2021-11-05 14:38
Sorry Filippo, I made my modifications to master already. Did not expect we need an extra branch for reviewing one page.

**Comment by DominicDirkx** [comment] 2021-11-05 15:48
Does this mean that the issue is resolved, or do the two branches need to be merged?

**Comment by FilippoOggionni** [comment] 2021-11-05 16:20
My modifications are in the branch, so I will open a pull request. 

In general, I would recommend working on branches different from master. This does not mean that each feature needs its own branch (although possible and to some point desirable), but each issue should clearly state which branch we are working on to make sure that we are all working on the same branch.

Another example: for the list of available acceleration/environment models, @jo11he and I worked on `user-guide-restyling`, but @DominicDirkx solved the TODOs on `master` (after merging, I believe). I did not know about this and I was making my final modifications for #24 still in `user-guide-restyling`. I found out half-way through the process and had to add the new additions from `master` into `user-guide-restyling` manually, because half of the file was already modified... If this can be avoided in the future, it would save everybody some time 😬

**Comment by FilippoOggionni** [comment] 2021-11-05 17:19
@DominicDirkx I opened a pull request (linked above). Please let me know if you or I should merge it

**Comment by DominicDirkx** [comment] 2021-11-05 19:43
Thanks, I've merged them, with a few small modifications. The biggest change is that I modified the big warning box to a new section. If you think this was a bad call, feel free to reopen this issue to let me know :)

**Closed** 2021-11-05 19:42 UTC
Labels: documentation

**Comment by FilippoOggionni** [comment] 2021-11-06 09:02
Looks great! Let's leave it as you made it.
Yeah, I do like all kind of sphinx-generated boxes and sometimes I tend to abuse of them a bit... 😆
